In [10]:
#1. Write a program to print the given number is odd or even.
num=int(input("Enter a number:"))
if num%2 ==0 :
    print("The number is even")
else:
    print("The number is odd")

Enter a number: 64


The number is even


In [11]:
#2. Write a program to find the given number is positive or negative.
num=int(input("Enter a number:"))
if num>=0:
    print("The number is positive")
else:
    print("The number is negative")

Enter a number: -10


The number is negative


In [12]:
#3. Write a program to find the sum of two numbers
def add(a,b):
    return a+b
a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
res=add(a,b)
print("The sum is:",res)

Enter first number: 7
Enter second number: 17


The sum is: 24


In [13]:
#4. Write a program to find if the given number is prime or not.
num=int(input("Enter a number:"))
c=0
for i in range(2,num):
    if num%i==0:
        c+=1
        break
if c==1:
    print("Number is not prime")
else:
    print("Number is prime")

Enter a number: 91


Number is not prime


In [8]:
#5. Write a program to check if the given number is palindrome or not.
num=int(input("Enter a number:"))
rem=0
temp=num
while num>0:
    dig=num%10
    rem=rem*10+dig
    num=num//10
if (rem==temp):
    print("The given number is palindrome")
else:
    print("The given number is not a palindrome")

Enter a number: 5005


The given number is palindrome


In [18]:
#6. Write a program to check if the given number is Armstrong or not.

num = int(input("Enter a number: "))
num_len=len(str(num))

sum = 0

temp = num
while temp > 0:
    digit = temp % 10
    sum += digit ** num_len
    temp //= 10

if num == sum:
    print(num, "is an Armstrong number")
else:
    print(num, "is not an Armstrong number")


Enter a number:  1634


1634 is an Armstrong number


In [19]:
#7. Write a program to check if the given strings are anagram or not.
def are_anagrams(str1, str2):
    
    str1 = str1.lower()
    str2 = str2.lower()

    sorted_str1 = sorted(str1)
    sorted_str2 = sorted(str2)

    if sorted_str1 == sorted_str2:
        print(f"{str1} and {str2} are anagrams.")
    else:
        print(f"{str1} and {str2} are not anagrams.")

are_anagrams("Race", "Care")

race and care are anagrams.


In [22]:
#8. Write a program to find a maximum of two numbers.
def max(num1,num2):
    return num1>num2
num1=int(input("Enter a number:"))
num2=int(input("Enter a number:"))
max_val=max(num1,num2)
if (max_val==True):
    print(num1,'is greater')
else:
    print(num2,'is greater')

Enter a number: 89
Enter a number: 45


89 is greater


In [24]:
#9. Write a program to find a minimum of two numbers.
def min(num1,num2):
    return num1<num2
num1=int(input("Enter a number:"))
num2=int(input("Enter a number:"))
min_val=min(num1,num2)
if (max_val==True):
    print(num2,'is smaller')
else:
    print(num1,'is smaller')

Enter a number: 45
Enter a number: 13


13 is smaller


In [32]:
#10.Write a program to find a maximum of three numbers.
def max(a,b,c):
    if (a>b) and (a>c):
        print(a,"is greatest")
    elif (b>c):
        print(b,"is greatest")
    else:
        print(c,"is greatest")
print("Enter 3 numbers")
a=int(input("Enter a number:"))
b=int(input("Enter a number:"))
c=int(input("Enter a number:"))
max(a,b,c)

Enter 3 numbers


Enter a number: 84
Enter a number: 101
Enter a number: 50


101 is greatest


In [35]:
#1. How do you find the indices of the maximum value in a NumPy array?
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr.argmax())

4


In [36]:
#2. How do you find the indices of the minimum value in a NumPy array?
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr.argmin())

0


In [38]:
#3. How do you create a NumPy array with a specified data type?
import numpy as np
myList = [1.5, 2.5, 3.5, 4.5, 5.5]
myArr = np.array(myList, dtype='int')
print(myArr)
print("Data type of array:", myArr.dtype)


[1 2 3 4 5]
Data type of array: int32


In [44]:
#4. In NumPy, how do I change the data type of an array?
import numpy as np
myArr = np.array([1, 2, 3], dtype='float64')
newTypeArr = myArr.astype(int)  
print(newTypeArr)


[1 2 3]


In [47]:
#5. How to add matrices using NumPy?
import numpy as np 
m1=np.array([[15,25],[35,45]])
m2=np.array([[55,65],[75,85]])
m3=np.add(m1,m2)
print(m3)

[[ 70  90]
 [110 130]]


In [48]:
#6. How to multiply matrices using NumPy?
import numpy as np 
m1=np.array([[15,25],[35,45]])
m2=np.array([[55,65],[75,85]])
m3=np.multiply(m1,m2)
print(m3)

[[ 825 1625]
 [2625 3825]]


In [52]:
#7. How to find the transpose of the matrix using NumPy?
import numpy as np
m1=np.array([[15,25],[35,45]])
transposed_m1=np.transpose(m1)
print(transposed_m1)

[[15 35]
 [25 45]]


In [64]:
#8. What is array slicing and how do you do it in NumPy?
import numpy as np
m2=np.array([[55,65,15,12],[75,85,12,11]])
print(m2[1,1:3])

[85 12]


In [67]:
#9. Create array by using arrange() function?
import numpy as np
my_array = np.arange(start=0, stop=100, step=10)
print(my_array)

[ 0 10 20 30 40 50 60 70 80 90]


In [9]:
#10.How do you split a NumPy array into multiple sub-arrays?
import numpy as np
my_array=np.array([10, 20, 30, 40, 50, 60, 70, 80, 90,100])
print(np.split(my_array,5))

[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80]), array([ 90, 100])]


In [5]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.5 MB 4.2 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/11.5 MB 3.4 MB/s eta 0:00:04
   -------- ------------------------------- 2.4/11.5 MB 3.9 MB/s eta 0:00:03
   ------------- -------------------------- 3.9/11.5 MB 4.8 MB/s eta 0:00:02
   ------------------ --------------------- 5.2/11.5 MB 5.3 MB/s eta 0:00:02
   ----------------------- ---------------- 6.8/11.5 MB 5.6 MB/s eta 0:00:01
   ------------------------------ --------- 8.7/11.5 MB 6.1 MB/s eta 0:00:01
   ------------------------------- -------- 9.2/11.5 MB 5.8 MB/s eta 0:00:01
   ---------------------------------- ----- 10.0/11.5 MB 5.5 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.5 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 5.0 MB/s eta 0:00:01
  

In [8]:
#1. Find the shape of the Dataset
import pandas as pd
data=pd.read_csv('heart.csv')
print(data.shape)

(1025, 14)


In [11]:
# 2. Display Top 5 Rows of The Dataset
print(data.head(5))

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0  


In [12]:
#3. Check The Last 5 Rows of The Dataset
print(data.tail(5))

      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  


In [13]:
# 4. Find Shape of Our Dataset (Number of Rows And Number of Columns)
print(data.shape)

(1025, 14)


In [14]:
# 5. Get Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement
print(data.dtypes)

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object


In [15]:
# 6. Check Null Values In The Dataset
data.isnull()

age    sex     cp  trestbps   chol    fbs  restecg  thalach  exang  \
0     False  False  False     False  False  False    False    False  False   
1     False  False  False     False  False  False    False    False  False   
2     False  False  False     False  False  False    False    False  False   
3     False  False  False     False  False  False    False    False  False   
4     False  False  False     False  False  False    False    False  False   
...     ...    ...    ...       ...    ...    ...      ...      ...    ...   
1020  False  False  False     False  False  False    False    False  False   
1021  False  False  False     False  False  False    False    False  False   
1022  False  False  False     False  False  False    False    False  False   
1023  False  False  False     False  False  False    False    False  False   
1024  False  False  False     False  False  False    False    False  False   

      oldpeak  slope     ca   thal  target  
0       False  False  False  False   False  
1       False  False  False  False   False  
2       False  False  False  False   False  
3       False  False  False  False   False  
4       False  False  False  False   False  
...       ...    ...    ...    ...     ...  
1020    False  False  False  False   False  
1021    False  False  False  False   False  
1022    False  False  False  False   False  
1023    False  False  False  False   False  
1024    False  False  False  False   False  

[1025 rows x 14 columns]

In [19]:
# 7. Check For Duplicate Data and Drop Them
data.drop_duplicates()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     52    1   0       125   212    0        1      168      0      1.0   
1     53    1   0       140   203    1        0      155      1      3.1   
2     70    1   0       145   174    0        1      125      1      2.6   
3     61    1   0       148   203    0        1      161      0      0.0   
4     62    0   0       138   294    1        1      106      0      1.9   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
723   68    0   2       120   211    0        0      115      0      1.5   
733   44    0   2       108   141    0        1      175      0      0.6   
739   52    1   0       128   255    0        1      161      1      0.0   
843   59    1   3       160   273    0        0      125      0      0.0   
878   54    1   0       120   188    0        1      113      0      1.4   

     slope  ca  thal  target  
0        2   2     3       0  
1        0   0     3       0  
2        0   0     3       0  
3        2   1     3       0  
4        1   3     2       0  
..     ...  ..   ...     ...  
723      1   0     2       1  
733      1   0     2       1  
739      2   1     3       0  
843      2   0     2       0  
878      1   1     3       0  

[302 rows x 14 columns]

In [20]:
#  8. Get Overall Statistics About The Dataset
data.describe()

age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000   
mean     54.434146     0.695610     0.942439   131.611707   246.00000   
std       9.072290     0.460373     1.029641    17.516718    51.59251   
min      29.000000     0.000000     0.000000    94.000000   126.00000   
25%      48.000000     0.000000     0.000000   120.000000   211.00000   
50%      56.000000     1.000000     1.000000   130.000000   240.00000   
75%      61.000000     1.000000     2.000000   140.000000   275.00000   
max      77.000000     1.000000     3.000000   200.000000   564.00000   

               fbs      restecg      thalach        exang      oldpeak  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000   
mean      0.149268     0.529756   149.114146     0.336585     1.071512   
std       0.356527     0.527878    23.005724     0.472772     1.175053   
min       0.000000     0.000000    71.000000     0.000000     0.000000   
25%       0.000000     0.000000   132.000000     0.000000     0.000000   
50%       0.000000     1.000000   152.000000     0.000000     0.800000   
75%       0.000000     1.000000   166.000000     1.000000     1.800000   
max       1.000000     2.000000   202.000000     1.000000     6.200000   

             slope           ca         thal       target  
count  1025.000000  1025.000000  1025.000000  1025.000000  
mean      1.385366     0.754146     2.323902     0.513171  
std       0.617755     1.030798     0.620660     0.500070  
min       0.000000     0.000000     0.000000     0.000000  
25%       1.000000     0.000000     2.000000     0.000000  
50%       1.000000     0.000000     2.000000     1.000000  
75%       2.000000     1.000000     3.000000     1.000000  
max       2.000000     4.000000     3.000000     1.000000

In [29]:
# 9. Find Count of Male & Female in this Dataset.
grouped=data.groupby("sex")
grouped.groups
agg=grouped.agg({"sex":"count"})
print(agg)

     sex
sex     
0    312
1    713


In [45]:
# 10. How Many People Have Heart Disease, And How Many Don't Have Heart Disease In This Dataset?
import numpy as np
grouped=data.groupby("target")
grouped.groups
agge=grouped.agg({"target":"count"})
print(agge)

        target
target        
0          499
1          526
